name: Deploy CDK Stack
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: docker build -t lambda-package .
      - name: Create Docker container
        run: docker create --name lambda-container lambda-package
      - name: Copy packaged Lambda function
        run: docker cp lambda-container:/lambda ./lambda_package
      - name: Zip Lambda function
        run: |
          cd lambda_package
          zip -r9 ../lambda_function.zip .
          cd ..
      - name: Install CDK
        run: npm install -g aws-cdk
      - name: Install CDK dependencies
        run: |
          cd cdk
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy CDK stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: cdk deploy --require-approval never

